apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-server-pvc
  labels:
    app: tc-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard